[[redirects]]
  from = "/notes"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/notes/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "https://applicationnotes.000webhostapp.com/api/notes"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}